# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d994ec4372ac11aa29f14ce12af837c76df7468d75d044fced1ba65d0d99652de1fb850fa624f9538ad6d691ec3290ec0a66a792c9b51d63b2abb570eb5000bc

test:
  secret_key_base: 20671b5755f6d127a0fd5b8bb09aee6bb2e5c261c696ad9c5ebdca8dc73d7ce0afee99e5d62e2ae8c4ecbe9c20ab25678eb7b6268cc7e7dfc750d05b28da867b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
